services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - sqlite-data:/app/data
    env_file:
      - backend/.env
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped

volumes:
  sqlite-data:
    driver: local
